FROM nginx:alpine as base

# Working DIR
WORKDIR /usr/src/app

# Copy everything from current Folder
RUN curl -L https://github.com/ipfs/ipfs-webui/releases/download/v2.15.0/ipfs-webui.tar.gz > ipfs-webui.tar.gz
RUN tar --extract --file ipfs-webui.tar.gz
RUN rm ipfs-webui.tar.gz

# A minimal NGINX configuration
RUN echo 'server {\
  listen       8080;\
  server_name  localhost;\
  location / {\
  root   /usr/src/app/build;\
  index  index.html index.htm;\
  try_files $uri /index.html;\
  }\
  }' > /etc/nginx/conf.d/default.conf

RUN mkdir /run/nginx
EXPOSE 8080

# Serve the prod build
CMD ["nginx", "-g", "daemon off;"]